CONFIG_ZMK_KEYBOARD_NAME="sosho"

#BLE connect
CONFIG_ZMK_BLE=y
#CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
#CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
#CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

#ZMK STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

#enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#enable mouse
CONFIG_ZMK_MOUSE=y

#SPI
CONFIG_ZMK_POINTING=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_INIT_PRIORITY=99
#Glidepoint
CONFIG_INPUT_PINNACLE=y

#encoder sensitive
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=128

#use NFC pins
CONFIG_NFCT_PINS_AS_GPIOS=y

#RGBLED_WIDGET
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

#BATTERY
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SLEEP=y
CONFIG_BT_BAS=y

#SPLIT
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#CONFIG_ZMK_USB_LOGGING=y