file_format: "1"
id: sosho
name: sosho
type: shield
url: https://github.com/abababababababa/ZMK_sosho_test
requires: [seeeduino_xiao_ble]
features:
  - keys
  - pointer
  - studio
  - encoder
siblings:
  - sosho_R
  - sosho_L